# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(299, 292)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 731, 611))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.plainTextEdit_Result = QtWidgets.QPlainTextEdit(self.page)
        self.plainTextEdit_Result.setGeometry(QtCore.QRect(250, 40, 191, 61))
        self.plainTextEdit_Result.setObjectName("plainTextEdit_Result")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 231, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 90, 25))
        self.label_2.setObjectName("label_2")
        self.label_1 = QtWidgets.QLabel(self.page)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 180, 25))
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setObjectName("label_1")
        self.Button_7 = QtWidgets.QPushButton(self.page)
        self.Button_7.setGeometry(QtCore.QRect(11, 111, 73, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_7.sizePolicy().hasHeightForWidth())
        self.Button_7.setSizePolicy(sizePolicy)
        self.Button_7.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_7.setIconSize(QtCore.QSize(16, 16))
        self.Button_7.setCheckable(False)
        self.Button_7.setChecked(False)
        self.Button_7.setObjectName("Button_7")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Button_7)
        self.Button_8 = QtWidgets.QPushButton(self.page)
        self.Button_8.setGeometry(QtCore.QRect(90, 111, 72, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_8.sizePolicy().hasHeightForWidth())
        self.Button_8.setSizePolicy(sizePolicy)
        self.Button_8.setObjectName("Button_8")
        self.buttonGroup.addButton(self.Button_8)
        self.Button_9 = QtWidgets.QPushButton(self.page)
        self.Button_9.setGeometry(QtCore.QRect(168, 111, 72, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_9.sizePolicy().hasHeightForWidth())
        self.Button_9.setSizePolicy(sizePolicy)
        self.Button_9.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_9.setObjectName("Button_9")
        self.buttonGroup.addButton(self.Button_9)
        self.Button_4 = QtWidgets.QPushButton(self.page)
        self.Button_4.setGeometry(QtCore.QRect(11, 169, 73, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_4.sizePolicy().hasHeightForWidth())
        self.Button_4.setSizePolicy(sizePolicy)
        self.Button_4.setObjectName("Button_4")
        self.buttonGroup.addButton(self.Button_4)
        self.Button_5 = QtWidgets.QPushButton(self.page)
        self.Button_5.setGeometry(QtCore.QRect(90, 169, 72, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_5.sizePolicy().hasHeightForWidth())
        self.Button_5.setSizePolicy(sizePolicy)
        self.Button_5.setObjectName("Button_5")
        self.buttonGroup.addButton(self.Button_5)
        self.Button_6 = QtWidgets.QPushButton(self.page)
        self.Button_6.setGeometry(QtCore.QRect(168, 169, 72, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_6.sizePolicy().hasHeightForWidth())
        self.Button_6.setSizePolicy(sizePolicy)
        self.Button_6.setObjectName("Button_6")
        self.buttonGroup.addButton(self.Button_6)
        self.Button_1 = QtWidgets.QPushButton(self.page)
        self.Button_1.setGeometry(QtCore.QRect(11, 227, 73, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_1.sizePolicy().hasHeightForWidth())
        self.Button_1.setSizePolicy(sizePolicy)
        self.Button_1.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_1.setObjectName("Button_1")
        self.buttonGroup.addButton(self.Button_1)
        self.Button_2 = QtWidgets.QPushButton(self.page)
        self.Button_2.setGeometry(QtCore.QRect(90, 227, 72, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_2.sizePolicy().hasHeightForWidth())
        self.Button_2.setSizePolicy(sizePolicy)
        self.Button_2.setObjectName("Button_2")
        self.buttonGroup.addButton(self.Button_2)
        self.Button_3 = QtWidgets.QPushButton(self.page)
        self.Button_3.setGeometry(QtCore.QRect(168, 227, 72, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_3.sizePolicy().hasHeightForWidth())
        self.Button_3.setSizePolicy(sizePolicy)
        self.Button_3.setObjectName("Button_3")
        self.buttonGroup.addButton(self.Button_3)
        self.Button_0 = QtWidgets.QPushButton(self.page)
        self.Button_0.setGeometry(QtCore.QRect(11, 285, 73, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_0.sizePolicy().hasHeightForWidth())
        self.Button_0.setSizePolicy(sizePolicy)
        self.Button_0.setObjectName("Button_0")
        self.buttonGroup.addButton(self.Button_0)
        self.Button_dot = QtWidgets.QPushButton(self.page)
        self.Button_dot.setGeometry(QtCore.QRect(90, 285, 72, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_dot.sizePolicy().hasHeightForWidth())
        self.Button_dot.setSizePolicy(sizePolicy)
        self.Button_dot.setObjectName("Button_dot")
        self.Button_dec = QtWidgets.QPushButton(self.page)
        self.Button_dec.setGeometry(QtCore.QRect(168, 285, 72, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_dec.sizePolicy().hasHeightForWidth())
        self.Button_dec.setSizePolicy(sizePolicy)
        self.Button_dec.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_dec.setObjectName("Button_dec")
        self.Button_grad = QtWidgets.QPushButton(self.page)
        self.Button_grad.setGeometry(QtCore.QRect(251, 378, 92, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_grad.sizePolicy().hasHeightForWidth())
        self.Button_grad.setSizePolicy(sizePolicy)
        self.Button_grad.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_grad.setObjectName("Button_grad")
        self.Button_clean = QtWidgets.QPushButton(self.page)
        self.Button_clean.setGeometry(QtCore.QRect(251, 188, 92, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_clean.sizePolicy().hasHeightForWidth())
        self.Button_clean.setSizePolicy(sizePolicy)
        self.Button_clean.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_clean.setObjectName("Button_clean")
        self.Button_result = QtWidgets.QPushButton(self.page)
        self.Button_result.setGeometry(QtCore.QRect(251, 111, 189, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_result.sizePolicy().hasHeightForWidth())
        self.Button_result.setSizePolicy(sizePolicy)
        self.Button_result.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_result.setObjectName("Button_result")
        self.Button_sum = QtWidgets.QPushButton(self.page)
        self.Button_sum.setGeometry(QtCore.QRect(251, 226, 92, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_sum.sizePolicy().hasHeightForWidth())
        self.Button_sum.setSizePolicy(sizePolicy)
        self.Button_sum.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_sum.setObjectName("Button_sum")
        self.Button_dergee = QtWidgets.QPushButton(self.page)
        self.Button_dergee.setGeometry(QtCore.QRect(251, 340, 92, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_dergee.sizePolicy().hasHeightForWidth())
        self.Button_dergee.setSizePolicy(sizePolicy)
        self.Button_dergee.setStyleSheet("font: 75 20pt \"Noto Sans\";     \n"
"")
        self.Button_dergee.setObjectName("Button_dergee")
        self.Button_right_parenthesis = QtWidgets.QPushButton(self.page)
        self.Button_right_parenthesis.setGeometry(QtCore.QRect(349, 302, 91, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_right_parenthesis.sizePolicy().hasHeightForWidth())
        self.Button_right_parenthesis.setSizePolicy(sizePolicy)
        self.Button_right_parenthesis.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_right_parenthesis.setObjectName("Button_right_parenthesis")
        self.Button_faqtorial = QtWidgets.QPushButton(self.page)
        self.Button_faqtorial.setGeometry(QtCore.QRect(349, 378, 91, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_faqtorial.sizePolicy().hasHeightForWidth())
        self.Button_faqtorial.setSizePolicy(sizePolicy)
        self.Button_faqtorial.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_faqtorial.setObjectName("Button_faqtorial")
        self.Button_sqrt = QtWidgets.QPushButton(self.page)
        self.Button_sqrt.setGeometry(QtCore.QRect(349, 340, 91, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_sqrt.sizePolicy().hasHeightForWidth())
        self.Button_sqrt.setSizePolicy(sizePolicy)
        self.Button_sqrt.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_sqrt.setObjectName("Button_sqrt")
        self.Button_mult = QtWidgets.QPushButton(self.page)
        self.Button_mult.setGeometry(QtCore.QRect(349, 264, 91, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_mult.sizePolicy().hasHeightForWidth())
        self.Button_mult.setSizePolicy(sizePolicy)
        self.Button_mult.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_mult.setObjectName("Button_mult")
        self.Button_left_parenthesis = QtWidgets.QPushButton(self.page)
        self.Button_left_parenthesis.setGeometry(QtCore.QRect(251, 302, 92, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_left_parenthesis.sizePolicy().hasHeightForWidth())
        self.Button_left_parenthesis.setSizePolicy(sizePolicy)
        self.Button_left_parenthesis.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_left_parenthesis.setObjectName("Button_left_parenthesis")
        self.Button_backspace = QtWidgets.QPushButton(self.page)
        self.Button_backspace.setGeometry(QtCore.QRect(349, 188, 91, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_backspace.sizePolicy().hasHeightForWidth())
        self.Button_backspace.setSizePolicy(sizePolicy)
        self.Button_backspace.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_backspace.setObjectName("Button_backspace")
        self.Button_diff = QtWidgets.QPushButton(self.page)
        self.Button_diff.setGeometry(QtCore.QRect(349, 226, 91, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_diff.sizePolicy().hasHeightForWidth())
        self.Button_diff.setSizePolicy(sizePolicy)
        self.Button_diff.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_diff.setObjectName("Button_diff")
        self.Button_divide = QtWidgets.QPushButton(self.page)
        self.Button_divide.setGeometry(QtCore.QRect(251, 264, 92, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_divide.sizePolicy().hasHeightForWidth())
        self.Button_divide.setSizePolicy(sizePolicy)
        self.Button_divide.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_divide.setObjectName("Button_divide")
        self.Button_left = QtWidgets.QPushButton(self.page)
        self.Button_left.setGeometry(QtCore.QRect(251, 150, 92, 32))
        self.Button_left.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_left.setObjectName("Button_left")
        self.Button_right = QtWidgets.QPushButton(self.page)
        self.Button_right.setGeometry(QtCore.QRect(349, 150, 91, 32))
        self.Button_right.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_right.setObjectName("Button_right")
        self.Button_tan = QtWidgets.QPushButton(self.page)
        self.Button_tan.setGeometry(QtCore.QRect(11, 379, 73, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_tan.sizePolicy().hasHeightForWidth())
        self.Button_tan.setSizePolicy(sizePolicy)
        self.Button_tan.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_tan.setObjectName("Button_tan")
        self.Button_e = QtWidgets.QPushButton(self.page)
        self.Button_e.setGeometry(QtCore.QRect(168, 379, 72, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_e.sizePolicy().hasHeightForWidth())
        self.Button_e.setSizePolicy(sizePolicy)
        self.Button_e.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_e.setObjectName("Button_e")
        self.Button_pi = QtWidgets.QPushButton(self.page)
        self.Button_pi.setGeometry(QtCore.QRect(90, 379, 72, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_pi.sizePolicy().hasHeightForWidth())
        self.Button_pi.setSizePolicy(sizePolicy)
        self.Button_pi.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_pi.setObjectName("Button_pi")
        self.Button_cos = QtWidgets.QPushButton(self.page)
        self.Button_cos.setGeometry(QtCore.QRect(11, 341, 73, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_cos.sizePolicy().hasHeightForWidth())
        self.Button_cos.setSizePolicy(sizePolicy)
        self.Button_cos.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_cos.setObjectName("Button_cos")
        self.Button_sin = QtWidgets.QPushButton(self.page)
        self.Button_sin.setGeometry(QtCore.QRect(90, 341, 72, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_sin.sizePolicy().hasHeightForWidth())
        self.Button_sin.setSizePolicy(sizePolicy)
        self.Button_sin.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_sin.setObjectName("Button_sin")
        self.Button_log = QtWidgets.QPushButton(self.page)
        self.Button_log.setGeometry(QtCore.QRect(168, 341, 72, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_log.sizePolicy().hasHeightForWidth())
        self.Button_log.setSizePolicy(sizePolicy)
        self.Button_log.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_log.setObjectName("Button_log")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_matrix_1 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_matrix_1.setGeometry(QtCore.QRect(10, 40, 325, 266))
        self.tableWidget_matrix_1.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_matrix_1.setRowCount(0)
        self.tableWidget_matrix_1.setColumnCount(0)
        self.tableWidget_matrix_1.setObjectName("tableWidget_matrix_1")
        self.tableWidget_matrix_1.horizontalHeader().setVisible(False)
        self.tableWidget_matrix_1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_matrix_1.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_matrix_1.horizontalHeader().setHighlightSections(False)
        self.tableWidget_matrix_1.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_matrix_1.verticalHeader().setVisible(False)
        self.tableWidget_matrix_1.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_matrix_1.verticalHeader().setHighlightSections(True)
        self.tableWidget_matrix_1.verticalHeader().setMinimumSectionSize(25)
        self.Button_result_martix = QtWidgets.QPushButton(self.page_2)
        self.Button_result_martix.setGeometry(QtCore.QRect(390, 340, 201, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_result_martix.sizePolicy().hasHeightForWidth())
        self.Button_result_martix.setSizePolicy(sizePolicy)
        self.Button_result_martix.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_result_martix.setObjectName("Button_result_martix")
        self.Button_clean_matrix = QtWidgets.QPushButton(self.page_2)
        self.Button_clean_matrix.setGeometry(QtCore.QRect(596, 340, 120, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_clean_matrix.sizePolicy().hasHeightForWidth())
        self.Button_clean_matrix.setSizePolicy(sizePolicy)
        self.Button_clean_matrix.setStyleSheet("font: 75 20pt \"Noto Sans\";")
        self.Button_clean_matrix.setObjectName("Button_clean_matrix")
        self.comboBox_matrix_1_collums = QtWidgets.QComboBox(self.page_2)
        self.comboBox_matrix_1_collums.setGeometry(QtCore.QRect(100, 10, 41, 25))
        self.comboBox_matrix_1_collums.setEditable(False)
        self.comboBox_matrix_1_collums.setMinimumContentsLength(0)
        self.comboBox_matrix_1_collums.setObjectName("comboBox_matrix_1_collums")
        self.comboBox_matrix_1_rows = QtWidgets.QComboBox(self.page_2)
        self.comboBox_matrix_1_rows.setGeometry(QtCore.QRect(220, 10, 41, 25))
        self.comboBox_matrix_1_rows.setEditable(False)
        self.comboBox_matrix_1_rows.setMaxCount(2147483647)
        self.comboBox_matrix_1_rows.setModelColumn(0)
        self.comboBox_matrix_1_rows.setObjectName("comboBox_matrix_1_rows")
        self.comboBox_result = QtWidgets.QComboBox(self.page_2)
        self.comboBox_result.setGeometry(QtCore.QRect(390, 10, 321, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_result.setFont(font)
        self.comboBox_result.setObjectName("comboBox_result")
        self.label_matrix_1_rows = QtWidgets.QLabel(self.page_2)
        self.label_matrix_1_rows.setGeometry(QtCore.QRect(160, 10, 61, 21))
        self.label_matrix_1_rows.setObjectName("label_matrix_1_rows")
        self.label_matrix_1_collums = QtWidgets.QLabel(self.page_2)
        self.label_matrix_1_collums.setGeometry(QtCore.QRect(20, 10, 71, 21))
        self.label_matrix_1_collums.setObjectName("label_matrix_1_collums")
        self.tableWidget_matrix_3 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_matrix_3.setGeometry(QtCore.QRect(390, 40, 325, 266))
        self.tableWidget_matrix_3.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_matrix_3.setRowCount(0)
        self.tableWidget_matrix_3.setColumnCount(0)
        self.tableWidget_matrix_3.setObjectName("tableWidget_matrix_3")
        self.tableWidget_matrix_3.horizontalHeader().setVisible(False)
        self.tableWidget_matrix_3.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget_matrix_3.horizontalHeader().setHighlightSections(True)
        self.tableWidget_matrix_3.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_matrix_3.verticalHeader().setVisible(False)
        self.tableWidget_matrix_3.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_matrix_3.verticalHeader().setMinimumSectionSize(25)
        self.frame_two_matrix = QtWidgets.QFrame(self.page_2)
        self.frame_two_matrix.setGeometry(QtCore.QRect(-10, 310, 380, 301))
        self.frame_two_matrix.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_two_matrix.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_two_matrix.setLineWidth(0)
        self.frame_two_matrix.setObjectName("frame_two_matrix")
        self.tableWidget_matrix_2 = QtWidgets.QTableWidget(self.frame_two_matrix)
        self.tableWidget_matrix_2.setGeometry(QtCore.QRect(20, 30, 325, 266))
        self.tableWidget_matrix_2.setLineWidth(0)
        self.tableWidget_matrix_2.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_matrix_2.setRowCount(0)
        self.tableWidget_matrix_2.setColumnCount(0)
        self.tableWidget_matrix_2.setObjectName("tableWidget_matrix_2")
        self.tableWidget_matrix_2.horizontalHeader().setVisible(False)
        self.tableWidget_matrix_2.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget_matrix_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_matrix_2.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_matrix_2.verticalHeader().setVisible(False)
        self.tableWidget_matrix_2.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_matrix_2.verticalHeader().setMinimumSectionSize(25)
        self.comboBox_matrix_2_rows = QtWidgets.QComboBox(self.frame_two_matrix)
        self.comboBox_matrix_2_rows.setGeometry(QtCore.QRect(240, 0, 41, 25))
        self.comboBox_matrix_2_rows.setObjectName("comboBox_matrix_2_rows")
        self.label_matrix_2_collums = QtWidgets.QLabel(self.frame_two_matrix)
        self.label_matrix_2_collums.setGeometry(QtCore.QRect(30, 0, 71, 21))
        self.label_matrix_2_collums.setObjectName("label_matrix_2_collums")
        self.label_matrix_2_rows = QtWidgets.QLabel(self.frame_two_matrix)
        self.label_matrix_2_rows.setGeometry(QtCore.QRect(170, 0, 61, 21))
        self.label_matrix_2_rows.setObjectName("label_matrix_2_rows")
        self.comboBox_matrix_2_collums = QtWidgets.QComboBox(self.frame_two_matrix)
        self.comboBox_matrix_2_collums.setGeometry(QtCore.QRect(110, 0, 41, 25))
        self.comboBox_matrix_2_collums.setObjectName("comboBox_matrix_2_collums")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(335, 120, 54, 61))
        self.label.setObjectName("label")
        self.frame_res = QtWidgets.QFrame(self.page_2)
        self.frame_res.setGeometry(QtCore.QRect(390, 100, 321, 121))
        self.frame_res.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_res.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_res.setLineWidth(0)
        self.frame_res.setObjectName("frame_res")
        self.lineEdit_result_matrix = QtWidgets.QLineEdit(self.frame_res)
        self.lineEdit_result_matrix.setGeometry(QtCore.QRect(10, 40, 301, 31))
        self.lineEdit_result_matrix.setObjectName("lineEdit_result_matrix")
        self.label_name_res = QtWidgets.QLabel(self.frame_res)
        self.label_name_res.setGeometry(QtCore.QRect(10, 10, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_name_res.setFont(font)
        self.label_name_res.setText("")
        self.label_name_res.setObjectName("label_name_res")
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setGeometry(QtCore.QRect(380, 410, 331, 91))
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.radio_treagle_down = QtWidgets.QRadioButton(self.groupBox)
        self.radio_treagle_down.setGeometry(QtCore.QRect(10, 30, 311, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radio_treagle_down.setFont(font)
        self.radio_treagle_down.setChecked(True)
        self.radio_treagle_down.setObjectName("radio_treagle_down")
        self.radio_treagle_up = QtWidgets.QRadioButton(self.groupBox)
        self.radio_treagle_up.setGeometry(QtCore.QRect(10, 60, 311, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radio_treagle_up.setFont(font)
        self.radio_treagle_up.setObjectName("radio_treagle_up")
        self.frame_enter_number = QtWidgets.QFrame(self.page_2)
        self.frame_enter_number.setGeometry(QtCore.QRect(380, 400, 371, 121))
        self.frame_enter_number.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_enter_number.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_enter_number.setLineWidth(0)
        self.frame_enter_number.setObjectName("frame_enter_number")
        self.lineEdit_enter_num_matrix = QtWidgets.QLineEdit(self.frame_enter_number)
        self.lineEdit_enter_num_matrix.setGeometry(QtCore.QRect(10, 40, 321, 31))
        self.lineEdit_enter_num_matrix.setObjectName("lineEdit_enter_num_matrix")
        self.label_name_func = QtWidgets.QLabel(self.frame_enter_number)
        self.label_name_func.setGeometry(QtCore.QRect(10, 10, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_name_func.setFont(font)
        self.label_name_func.setText("")
        self.label_name_func.setObjectName("label_name_func")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.lineEdit_con_input = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_con_input.setGeometry(QtCore.QRect(160, 10, 151, 31))
        self.lineEdit_con_input.setObjectName("lineEdit_con_input")
        self.lineEdit_con_output = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_con_output.setGeometry(QtCore.QRect(160, 90, 151, 31))
        self.lineEdit_con_output.setObjectName("lineEdit_con_output")
        self.comboBox_con_input = QtWidgets.QComboBox(self.page_3)
        self.comboBox_con_input.setGeometry(QtCore.QRect(320, 10, 151, 31))
        self.comboBox_con_input.setObjectName("comboBox_con_input")
        self.comboBox_con_output = QtWidgets.QComboBox(self.page_3)
        self.comboBox_con_output.setGeometry(QtCore.QRect(320, 90, 151, 31))
        self.comboBox_con_output.setObjectName("comboBox_con_output")
        self.listWidget = QtWidgets.QListWidget(self.page_3)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 141, 161))
        self.listWidget.setObjectName("listWidget")
        self.con_change = QtWidgets.QPushButton(self.page_3)
        self.con_change.setGeometry(QtCore.QRect(160, 50, 311, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.con_change.setFont(font)
        self.con_change.setObjectName("con_change")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 299, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu.addAction(self.action_6)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.comboBox_matrix_1_collums.setCurrentIndex(-1)
        self.comboBox_matrix_1_rows.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Ответ</span></p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Введите выражение</span></p></body></html>"))
        self.Button_7.setText(_translate("MainWindow", "7"))
        self.Button_8.setStyleSheet(_translate("MainWindow", "font: 75 20pt \"Noto Sans\";"))
        self.Button_8.setText(_translate("MainWindow", "8"))
        self.Button_9.setText(_translate("MainWindow", "9"))
        self.Button_4.setStyleSheet(_translate("MainWindow", "font: 75 20pt \"Noto Sans\";"))
        self.Button_4.setText(_translate("MainWindow", "4"))
        self.Button_5.setStyleSheet(_translate("MainWindow", "font: 75 20pt \"Noto Sans\";"))
        self.Button_5.setText(_translate("MainWindow", "5"))
        self.Button_6.setStyleSheet(_translate("MainWindow", "font: 75 20pt \"Noto Sans\";"))
        self.Button_6.setText(_translate("MainWindow", "6"))
        self.Button_1.setText(_translate("MainWindow", "1"))
        self.Button_2.setStyleSheet(_translate("MainWindow", "font: 75 20pt \"Noto Sans\";"))
        self.Button_2.setText(_translate("MainWindow", "2"))
        self.Button_3.setStyleSheet(_translate("MainWindow", "font: 75 20pt \"Noto Sans\";"))
        self.Button_3.setText(_translate("MainWindow", "3"))
        self.Button_0.setStyleSheet(_translate("MainWindow", "font: 75 20pt \"Noto Sans\";"))
        self.Button_0.setText(_translate("MainWindow", "0"))
        self.Button_dot.setStyleSheet(_translate("MainWindow", "font: 75 20pt \"Noto Sans\";"))
        self.Button_dot.setText(_translate("MainWindow", "."))
        self.Button_dec.setText(_translate("MainWindow", "1/x"))
        self.Button_grad.setText(_translate("MainWindow", "°"))
        self.Button_clean.setText(_translate("MainWindow", "C"))
        self.Button_result.setText(_translate("MainWindow", "="))
        self.Button_sum.setText(_translate("MainWindow", "+"))
        self.Button_dergee.setText(_translate("MainWindow", "^"))
        self.Button_right_parenthesis.setText(_translate("MainWindow", ")"))
        self.Button_faqtorial.setText(_translate("MainWindow", "n!"))
        self.Button_sqrt.setText(_translate("MainWindow", "√"))
        self.Button_mult.setText(_translate("MainWindow", "*"))
        self.Button_left_parenthesis.setText(_translate("MainWindow", "("))
        self.Button_backspace.setText(_translate("MainWindow", "←"))
        self.Button_diff.setText(_translate("MainWindow", "-"))
        self.Button_divide.setText(_translate("MainWindow", "/"))
        self.Button_left.setText(_translate("MainWindow", "⇐"))
        self.Button_right.setText(_translate("MainWindow", "⇒"))
        self.Button_tan.setText(_translate("MainWindow", "tan"))
        self.Button_e.setText(_translate("MainWindow", "e"))
        self.Button_pi.setText(_translate("MainWindow", "π"))
        self.Button_cos.setText(_translate("MainWindow", "cos"))
        self.Button_sin.setText(_translate("MainWindow", "sin"))
        self.Button_log.setText(_translate("MainWindow", "log"))
        self.Button_result_martix.setText(_translate("MainWindow", "="))
        self.Button_clean_matrix.setText(_translate("MainWindow", "C"))
        self.label_matrix_1_rows.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Строки</span></p></body></html>"))
        self.label_matrix_1_collums.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Столбцы</span></p></body></html>"))
        self.label_matrix_2_collums.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Столбцы</span></p></body></html>"))
        self.label_matrix_2_rows.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Строки</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">=</span></p></body></html>"))
        self.radio_treagle_down.setText(_translate("MainWindow", "Нули ниже главной диагонали"))
        self.radio_treagle_up.setText(_translate("MainWindow", "Нули выше главной диагонали"))
        self.con_change.setText(_translate("MainWindow", "⇆"))
        self.menu.setTitle(_translate("MainWindow", "Калькуляторы"))
        self.action_2.setText(_translate("MainWindow", "Обычный"))
        self.action_3.setText(_translate("MainWindow", "Матричный"))
        self.action_5.setText(_translate("MainWindow", "Выход"))
        self.action.setText(_translate("MainWindow", "Конвертер"))
        self.action_4.setText(_translate("MainWindow", "Геометрия"))
        self.action_6.setText(_translate("MainWindow", "?????"))

