# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 397)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 180, 25))
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setObjectName("label_1")
        self.plainTextEdit_Result = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Result.setGeometry(QtCore.QRect(200, 40, 90, 65))
        self.plainTextEdit_Result.setObjectName("plainTextEdit_Result")
        self.Button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_1.setGeometry(QtCore.QRect(10, 240, 50, 50))
        self.Button_1.setObjectName("Button_1")
        self.Button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_3.setGeometry(QtCore.QRect(140, 240, 50, 50))
        self.Button_3.setObjectName("Button_3")
        self.Button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_5.setGeometry(QtCore.QRect(75, 180, 50, 50))
        self.Button_5.setObjectName("Button_5")
        self.Button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_7.setGeometry(QtCore.QRect(10, 120, 50, 50))
        self.Button_7.setObjectName("Button_7")
        self.Button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_2.setGeometry(QtCore.QRect(75, 240, 50, 50))
        self.Button_2.setObjectName("Button_2")
        self.Button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_8.setGeometry(QtCore.QRect(75, 120, 50, 50))
        self.Button_8.setObjectName("Button_8")
        self.Button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_4.setGeometry(QtCore.QRect(10, 180, 50, 50))
        self.Button_4.setObjectName("Button_4")
        self.Button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_6.setGeometry(QtCore.QRect(140, 180, 50, 50))
        self.Button_6.setObjectName("Button_6")
        self.Button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_9.setGeometry(QtCore.QRect(140, 120, 50, 50))
        self.Button_9.setObjectName("Button_9")
        self.Button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_0.setGeometry(QtCore.QRect(10, 300, 115, 50))
        self.Button_0.setObjectName("Button_0")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 10, 90, 25))
        self.label_2.setObjectName("label_2")
        self.Button_dot = QtWidgets.QPushButton(self.centralwidget)
        self.Button_dot.setGeometry(QtCore.QRect(140, 300, 50, 50))
        self.Button_dot.setObjectName("Button_dot")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 181, 65))
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(200, 120, 91, 231))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Button_result = QtWidgets.QPushButton(self.widget)
        self.Button_result.setObjectName("Button_result")
        self.verticalLayout.addWidget(self.Button_result)
        self.Button_divide = QtWidgets.QPushButton(self.widget)
        self.Button_divide.setObjectName("Button_divide")
        self.verticalLayout.addWidget(self.Button_divide)
        self.Button_mult = QtWidgets.QPushButton(self.widget)
        self.Button_mult.setObjectName("Button_mult")
        self.verticalLayout.addWidget(self.Button_mult)
        self.Button_diff = QtWidgets.QPushButton(self.widget)
        self.Button_diff.setObjectName("Button_diff")
        self.verticalLayout.addWidget(self.Button_diff)
        self.Button_sum = QtWidgets.QPushButton(self.widget)
        self.Button_sum.setObjectName("Button_sum")
        self.verticalLayout.addWidget(self.Button_sum)
        self.Button_left_parenthesis = QtWidgets.QPushButton(self.widget)
        self.Button_left_parenthesis.setObjectName("Button_left_parenthesis")
        self.verticalLayout.addWidget(self.Button_left_parenthesis)
        self.Button_right_parenthesis = QtWidgets.QPushButton(self.widget)
        self.Button_right_parenthesis.setObjectName("Button_right_parenthesis")
        self.verticalLayout.addWidget(self.Button_right_parenthesis)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор "))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Введите выражение</span></p></body></html>"))
        self.Button_1.setText(_translate("MainWindow", "1"))
        self.Button_3.setText(_translate("MainWindow", "3"))
        self.Button_5.setText(_translate("MainWindow", "5"))
        self.Button_7.setText(_translate("MainWindow", "7"))
        self.Button_2.setText(_translate("MainWindow", "2"))
        self.Button_8.setText(_translate("MainWindow", "8"))
        self.Button_4.setText(_translate("MainWindow", "4"))
        self.Button_6.setText(_translate("MainWindow", "6"))
        self.Button_9.setText(_translate("MainWindow", "9"))
        self.Button_0.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Ответ</span></p></body></html>"))
        self.Button_dot.setText(_translate("MainWindow", "."))
        self.Button_result.setText(_translate("MainWindow", "="))
        self.Button_divide.setText(_translate("MainWindow", "/"))
        self.Button_mult.setText(_translate("MainWindow", "*"))
        self.Button_diff.setText(_translate("MainWindow", "-"))
        self.Button_sum.setText(_translate("MainWindow", "+"))
        self.Button_left_parenthesis.setText(_translate("MainWindow", "("))
        self.Button_right_parenthesis.setText(_translate("MainWindow", ")"))

